### ISSUE TITLE
Error installing module

### ISSUE THREAD

**Issue by videokid** [juergenweb/FieldtypeOpeningHours#1]
Trying to install the module:

`Parse Error: syntax error, unexpected ':', expecting ';' or '{' (line 147 of \site\modules\FieldtypeOpeningHours\InputfieldOpeningHours.module)`

ProcessWire 3.0.148

Kind regards,
 - Igor

**Comment by juergenweb** [comment]
Are you sure, that you are using PHP 7?

This is a conventional type hinting introduced in PHP7.

`public function sanitizeValidateValues(array $times, string $fieldName): array`

Please check your PHP version.

Best regards

**Comment by videokid** [comment]
I am sure I'm NOT using PHP7 and I know this was introduced in PHP7 ...
AFAIK, it's not mentioned minimum use requires PHP7, but now I do :-)

I guess you will not implement a fall-back... so this issue can be closed.
Thx for the prompt reply.

Kind regards,
 - Igor

**Comment by juergenweb** [comment]
Hello Igor,

it is defined in the getModulInfo() method, so in this case you should have to be warned before you click the install button.

`public static function getModuleInfo()
    {
        return array(
            'title' => 'Inputfield Opening Hours',
            'summary' => 'Renders an input field for entering opening hours',
            'version' => 1.1,
            'href' => 'https://github.com/juergenweb/FieldtypeOpeningHours',
            'icon' => 'clock-o',
            'permanent' => false,
            'requires' => [
                'PHP>=7.0.0',
                'ProcessWire>=3',
                'FieldtypeOpeningHours'
              ],
            'author' => 'Jürgen Kern'
        );
    }
`

As you can see PHP>= 7.0.0 is defined as minimum requirement. 

Type hinting is not necessary to make the module working, so you can remove every type hinting in the files - but you have to remove every type hinting (and of course other parts of the code such as array syntax with []).

Type hinting makes only the code quality better and the code more stable.

The best way to adapt the code for lower PHP versions is to run it through https://phpcodechecker.com/, set the PHP version to PHP 5 and change all the code lines which are not compatible with lower PHP versions. If there are no errors upload it once more and you are done.

Best regards

**Comment by videokid** [comment]
`As you can see PHP>= 7.0.0 is defined as minimum requirement.`

Mmm yes, and no, I wasn't prompted by a warning, weird... 
Thx for the additional information. I do have a live server with php 7.x, so I guess I'll install it on that one!

Kind regards and thanks for the module!
 - Igor

**Comment by juergenweb** [comment]
`As you can see PHP>= 7.0.0 is defined as minimum requirement.`

Really weird. I haven't tested it with lower PHP versions to check if there is a mistake in the method that prevents the warning (but I don't think so).
Ok, I will close this issue for now.

Have a nice day

Jürgen
