### ISSUE TITLE
Install issue due to functions API calls

### ISSUE THREAD

**Issue by flydev-fr** [juergenweb/FieldtypeOpeningHours#2]
Hi @juergenweb 

got an issue when installing the module, the cause of two call made with functions API which are not enabled by default on my setup, and I suppose in others people setup.

https://github.com/juergenweb/FieldtypeOpeningHours/blob/5ef1c35a7795d6c39f6f4b4b734f8c406c31fec3/InputfieldOpeningHours.module#L45-L46

**Comment by juergenweb** [comment]
According to the docs at https://processwire.com/docs/start/api-access/ the word "wire" was prepended on both function calls to make functions API available. Please check if it is working now.

Best regards

**Comment by flydev-fr** [comment]
Yes I know that. I posted the issue because I would need to enable functions API in order to use the module for only those two calls which could be writen like `$this->config` like the one preceding the call:

I changed 
`$this->config->styles->add(config()->urls->{$this->className} . 'openinghours.css?v='.$version);`
 to
`$this->config->styles->add($this->config->urls->{$this->className} . 'openinghours.css?v='.$version);`

I mean, I see no benefit to use functions API here 😆

**Comment by juergenweb** [comment]
Thanks for the hint. I have always set functions API to true, so I did not care about that in the past.
